spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hitsproj1
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/hitsproj1
    user: postgres
    password: password
    locations: classpath:migrations
  jpa:
    hibernate:
      ddl-auto: validate
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 4000000
      refresh-token:
        expiration: 80000000